/**
 * Custom title
 * This is a very custom OpenAPI schema
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { autoinject } from 'aurelia-framework';
import { HttpClient } from 'aurelia-http-client';
import { Api } from './Api';
import { AuthStorage } from './AuthStorage';
import {
  IMFPPPCountry,
  LunchoData,
} from './models';

/**
 * countryCodes - parameters interface
 */
export interface ICountryCodesParams {
}

/**
 * countryPPPs - parameters interface
 */
export interface ICountryPPPsParams {
}

/**
 * lunchoData - parameters interface
 */
export interface ILunchoDataParams {
  countryCode?: string;
  clientRegion?: string;
  cloudfrontViewerCountry?: string;
}

/**
 * lunchoDatas - parameters interface
 */
export interface ILunchoDatasParams {
}

/**
 * LunchoApi - API class
 */
@autoinject()
export class LunchoApi extends Api {

  /**
   * Creates a new LunchoApi class.
   *
   * @param httpClient The Aurelia HTTP client to be injected.
   * @param authStorage A storage for authentication data.
   */
  constructor(httpClient: HttpClient, authStorage: AuthStorage) {
    super(httpClient, authStorage);
  }

  /**
   * Countrycodes
   * Returns a list of supported country codes.
   */
  async countryCodes(): Promise<Array<string>> {
    // Verify required parameters are set

    // Create URL to call
    const url = `${this.basePath}/country-codes`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()

      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Countryppps
   * Returns country data for all countries.
   */
  async countryPPPs(): Promise<{ [key: string]: IMFPPPCountry; }> {
    // Verify required parameters are set

    // Create URL to call
    const url = `${this.basePath}/country-PPPs`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()

      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Lunchodata
   * Returns LunchoData that is needed to convert between Luncho and local currency of the countryCode. If the countryCode is not specified, estimate it from IP address.
   * @param params.countryCode 
   * @param params.clientRegion 
   * @param params.cloudfrontViewerCountry 
   */
  async lunchoData(params: ILunchoDataParams): Promise<LunchoData> {
    // Verify required parameters are set

    // Create URL to call
    const url = `${this.basePath}/luncho-data`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()
      // Set query parameters
      .withParams({ 
        'country_code': params['countryCode'],
      })
      .withHeader('client-region', params['clientRegion'])      .withHeader('cloudfront-viewer-country', params['cloudfrontViewerCountry'])
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Lunchodatas
   * Returns A list of LunchoDatas for all supported countries.
   */
  async lunchoDatas(): Promise<Array<LunchoData>> {
    // Verify required parameters are set

    // Create URL to call
    const url = `${this.basePath}/luncho-datas`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()

      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

}

