/**
 * Custom title
 * This is a very custom OpenAPI schema
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HTTPValidationError {
  detail?: Array<ValidationError>;
}


/**
 * Data needed to convert between Luncho and local currency. 
 */
export interface LunchoData {
  country_code: string;
  country_name: string;
  continent_code: string;
  currency_code: string;
  currency_name: string;
  exchange_rate?: number;
  ppp?: number;
  dollar_per_luncho: number;
}


export interface ValidationError {
  loc: Array<string>;
  msg: string;
  type: string;
}

