"""
    Custom title

    This is a very custom OpenAPI schema  # noqa: E501

    The version of the OpenAPI document: 2.5.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_convert_from_luncho(self):
        """Test case for convert_from_luncho

        Convert From Luncho  # noqa: E501
        """
        pass

    def test_convert_from_luncho_all(self):
        """Test case for convert_from_luncho_all

        Convert From Luncho All  # noqa: E501
        """
        pass

    def test_convert_from_luncho_dummy(self):
        """Test case for convert_from_luncho_dummy

        Convert From Luncho Dummy  # noqa: E501
        """
        pass

    def test_countries(self):
        """Test case for countries

        Countries  # noqa: E501
        """
        pass

    def test_test(self):
        """Test case for test

        Test  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
