* Luncho: Common Value Index for the economic inequality issue

** With 100 Luncho, you can have simple lunch in every country.

The main applications are *determining wages* and the *pricing of digital services*.

Suppose you are selling your digital service for $7 per month per user. That price may be good for
people living in advanced countries. But, how about for people in other countries? So many people
might feel that $7 was too expensive.

In that case you can sell your digital service at 100 Luncho per month, for example. Your site can
show both a Luncho price and its local prices using this Luncho server.

- In USA
  Product A  100 Luncho per month, $7.12 ($7.12 USD)

- In India
  Product A  100 Luncho per month, 157.51 Rupee ($2.14 USD)

- In Finland
  Product A  100 Luncho per month, 6.08 Euro ($7.35 USD)

- In Peru
  Product A  100 Luncho per month, 12.84 Sol ($3.45 USD)

It seems your revenue goes down? Maybe no because people who couldn't buy your digital service would
become to buy it. You can expect more users will utilize your service.


** Who should use Luncho?

- Digital service providers
- Global companies that pay wages

** How it works?

Luncho is calculated using [[https://www.worldbank.org/en/programs/icp][implied Purchase Power Parity (PPP) in the latest International
Comparison Program (ICP)]], [[https://www.imf.org/en/About/Factsheets/Sheets/2016/08/01/14/51/Special-Drawing-Right-SDR][IMF's Special Drawing Rights (SDR)]], and the exchange rate of every currency.

A PPP shows the price level in a country, that is, how much goods and services are in the
country. The SDR is a mixture of major currencies including US Dollar, Euro, GB Pound, Japanese Yen,
and Chinese Yuan. The SDR and exchange rates are updated every hour.

100 Luncho is 5 SDR and it's converted into local currency using the PPP.

The PPP is based on the latest International Comparison Program (ICP) lead by the World Bank. The
ICP is tremendous effort done every five years by many people that investigates price levels of [[https://openknowledge.worldbank.org/bitstream/handle/10986/33623/9781464815300.pdf][many
items such as bread, pork, cheese, sugar, gas, medical services, cars, etc. in all countries]]. Luncho
uses Actual Individual Consumption (AIC) per capita that represents statistical price levels in
daily lives for wide applications, not actual lunch prices.

Thus, with 100 Luncho in a country, you can expect to have simple lunch in a restaurant for local
residents. Caution that restaurant for tourists should be much more expensive actually.

It's similar to [[https://www.economist.com/big-mac-index][Big Mac index]], but considers much more factors.


** Data

- PPP from IMF World Economic Outlook (October 2020)
  - data/imf-dm-export-20201110.csv
  - Press "All Data" to get it at [[https://www.imf.org/external/datamapper/PPPEX@WEO/OEMDC/ADVEC/WEOWORLD][here]]
  - 194 countries and regions
  - Country name is defined as "Table Name" in the following ICP-2017 metadata

- ICP-2017 metadata
  - data/Data_Extract_From_ICP_2017_Metadata.csv
  - Extracted the following metadata from [[https://databank.worldbank.org/source/icp-2017?preview=on][ICP-2017 database]]
  - Code,Long Name,Currency Unit,Table Name,Household consumption price survey: Geographical coverage
  - Examples

     AFG,Islamic State of Afghanistan,AFN: Afghani,Afghanistan,
     ALB,Republic of Albania,ALL: Lek,Albania,Urban only
     DZA,People's Democratic Republic of Algeria,DZD: Algerian Dinar,Algeria,Urban and Rural

- ICP-2017 Purchasing power parity (PPP) (US$ = 1)
  - Extracted the following from [[https://databank.worldbank.org/source/icp-2017?preview=on][ICP-2017 database]]
    - Actual Individual Consumption (AIC) per capita

** Author

Dr HIRANO Satoshi, AIST

** Acknowledgment

- Many people who worked hard for the International Comparison Program
- The Aurelia core team for Aurelia framework
- MaterializeCSS and Aurelia Materialize Bridge for CSS
- Starlette, Pydantic, and FastAPI for Web framework
- SQLAlchemy for database access
- OpenAPI for generating client libraries
- Fixer.io for exchange rates
- AIST and Human Informatics and Interaction Research Institute (HIIRI) for support

** MIT License

Copyright 2019-2021 The National Institute of Advanced Industrial Science and Technology (AIST), Japan

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
