** Deprecated. Visit [[https://github.com/Peace-and-Passion/luncho][Luncho de Peace at https://github.com/Peace-and-Passion/luncho]] for a new version.

*** Common value index that you can have simple lunch in every country with 100 Luncho.

Useful for currency conversion on pricing pages and wages for mitigating the inequality problem among countries. It's based on purchase power parity (PPP) and World comparison Program (ICP).

***

A luncho value shows the same value in any country taking its price levels into account. For example, with
      100 Luncho, you can have simple lunch in India, in Brazil, in USA, in Japan, and in any other
      countries.

In India 100 Luncho is equivalent to 160 rupee ($2.19 US dollar), while the same 100 Luncho
      is equivalent to 17 real ($3.12 US dollar) in Brazil. In USA, 100 Luncho is about $7.21 US
        dollar. All are the same value because everything is just 100 Luncho.

*** [[https://luncho-de-peace.org][Demo on the official Luncho de Peace web site]]
*** [[https://luncho-de-peace.org/#/about][Detail about Luncho, how it works]]

*** Usages

- [[./luncho-python/README.markdown][README for Python client library]]
- [[./luncho-typescript-fetch/README.markdown][README for TypeScript and Fetch client library]]

- [[./server/README.org][README for the Luncho server]]
- [[./app/README.org][README for the Luncho app]]

Send PRs if you make client libs for other languages.

*** API change

- Added get_luncho_from_currency() and get_currency_from_US_dollar().
- 100 Luncho is 6 SDR since 16th March, 2023.

*** Bonus

*Grow your product with Luncho.*

Once you use Luncho in your pricing page, people in developing countries who are not able to
buy your digital service will become to afford to buy it. Luncho will accelerate growth of
your user base and your revenue beyond the current ones without Luncho.

*** Note

Luncho de Peace is a derived work of AIST Luncho.
