"""
    Client library for Luncho API. 

    Use luncho.ts and luncho.py rather than LunchoAPI.ts and others.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import luncho-python
from luncho-python.api.luncho_api import LunchoApi  # noqa: E501


class TestLunchoApi(unittest.TestCase):
    """LunchoApi unit test stubs"""

    def setUp(self):
        self.api = LunchoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_all_luncho_data(self):
        """Test case for all_luncho_data

        All Luncho Data  # noqa: E501
        """
        pass

    def test_countries(self):
        """Test case for countries

        Countries  # noqa: E501
        """
        pass

    def test_country_code(self):
        """Test case for country_code

        Country Code  # noqa: E501
        """
        pass

    def test_health(self):
        """Test case for health

        Health  # noqa: E501
        """
        pass

    def test_luncho_data(self):
        """Test case for luncho_data

        Luncho Data  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
