/**
 * Client library for Luncho API. 
 * Use luncho.ts and luncho.py rather than LunchoAPI.ts and others.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HTTPValidationError {
  detail?: Array<ValidationError>;
}


/**
 * Data needed to convert between Luncho and local currency. If data for the country is not available, either ppp or exchange_rate is 0.
 */
export interface LunchoData {
  country_code: string;
  country_name: string;
  continent_code: string;
  currency_code: string;
  currency_name: string;
  exchange_rate: number;
  ppp: number;
  dollar_per_luncho: number;
  expiration: number;
}


export interface ValidationError {
  loc: Array<string | number>;
  msg: string;
  type: string;
}

