"""
    Custom title

    This is a very custom OpenAPI schema  # noqa: E501

    The version of the OpenAPI document: 2.5.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.imfppp_country import IMFPPPCountry


class TestIMFPPPCountry(unittest.TestCase):
    """IMFPPPCountry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIMFPPPCountry(self):
        """Test IMFPPPCountry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IMFPPPCountry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
