"""
    Custom title

    This is a very custom OpenAPI schema  # noqa: E501

    The version of the OpenAPI document: 2.5.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.luncho_api import LunchoApi  # noqa: E501


class TestLunchoApi(unittest.TestCase):
    """LunchoApi unit test stubs"""

    def setUp(self):
        self.api = LunchoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_luncho(self):
        """Test case for luncho

        Luncho  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
