* Luncho Server

** What it is?

  - The Luncho server provides API so that your web site can show both Luncho price and local prices.
  - The Luncho server provides OpenAPI so tha you can generate client libraries.

** Requirements

  - An access key of Fixer to get exchange rate. Placeit in api_keys.py
  - Follow the Installation section to install the required packages.
  - Pypy3 (Python compiler)
  - FastAPI (Web framework)

** Installation

*** Create an account on Fixer to get exchange rate

  - Place your Fixer access key in api_keys.py.

    Fixer_Access_Key = 'XXXXXXXX'

*** Local installation

  - [[https://www.pypy.org/download.html][Install pypy3]]
   - (Mac) brew install pypy3
  - Install Rust that is required to run pip
   - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
   - (restart bash to add rustup to PATH)
   - rustup install nightly ; rustup default nightly
  - Run install script
   - bin/install-packages.sh
  - You have pypyenv dir that includes site-packages.

*** Generate client library and link

  - pypy3 main.py gen
  - if you use yarn or npm, compile and link;
    - pushd ../client-libs/luncho_typescript-aurelia; yarn install; yarn link; popd
    - pushd ../app; yarn link "luncho_typescript-aurelia"


*** Run a local Luncho server
  - bin/start-gunicorn.sh

*** Docker installation

  - build
     docker compose build --progress plain
  - run
     docker run luncho-server_app
  - ps for containerID
     docker ps
  - kill
     docker kill containerID

** Limitations

  - The Luncho server refreshes exchange rates every one hour and tell clients to keep data for one
    hour since the last refresh. If you have multiple Luncho servers, the servers refresh exchange
    rates independently. You may get different results.


** Author

Dr HIRANO Satoshi, AIST

** MIT License

Copyright 2019-2021 The National Institute of Advanced Industrial Science and Technology (AIST), Japan

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
