"""
    Client library for Luncho API. 

    Use luncho.ts and luncho.py rather than LunchoAPI.ts and others.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import luncho_python
from luncho_python.model.luncho_data import LunchoData


class TestLunchoData(unittest.TestCase):
    """LunchoData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLunchoData(self):
        """Test LunchoData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LunchoData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
