"""
    Client library for Luncho API. 

    Use luncho.ts and luncho.py rather than LunchoAPI.ts and others.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import luncho_python
from luncho_python.api.luncho_api import LunchoApi  # noqa: E501


class TestLunchoApi(unittest.TestCase):
    """LunchoApi unit test stubs"""

    def setUp(self):
        self.api = LunchoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_countries(self):
        """Test case for countries

        Countries  # noqa: E501
        """
        pass

    def test_luncho_data(self):
        """Test case for luncho_data

        Lunchodata  # noqa: E501
        """
        pass

    def test_luncho_datas(self):
        """Test case for luncho_datas

        Lunchodatas  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
