/* tslint:disable */
/* eslint-disable */
/**
 * Custom title
 * This is a very custom OpenAPI schema
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IMFPPPCountry
 */
export interface IMFPPPCountry {
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof IMFPPPCountry
     */
    year_ppp?: { [key: string]: number; };
    /**
     * 
     * @type {string}
     * @memberof IMFPPPCountry
     */
    currency_code?: string;
    /**
     * 
     * @type {string}
     * @memberof IMFPPPCountry
     */
    currency_name?: string;
    /**
     * 
     * @type {string}
     * @memberof IMFPPPCountry
     */
    country_name?: string;
}

export function IMFPPPCountryFromJSON(json: any): IMFPPPCountry {
    return IMFPPPCountryFromJSONTyped(json, false);
}

export function IMFPPPCountryFromJSONTyped(json: any, ignoreDiscriminator: boolean): IMFPPPCountry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'year_ppp': !exists(json, 'year_ppp') ? undefined : json['year_ppp'],
        'currency_code': !exists(json, 'currency_code') ? undefined : json['currency_code'],
        'currency_name': !exists(json, 'currency_name') ? undefined : json['currency_name'],
        'country_name': !exists(json, 'country_name') ? undefined : json['country_name'],
    };
}

export function IMFPPPCountryToJSON(value?: IMFPPPCountry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'year_ppp': value.year_ppp,
        'currency_code': value.currency_code,
        'currency_name': value.currency_name,
        'country_name': value.country_name,
    };
}


